import React from 'react';
import { Shield, Printer, X } from 'lucide-react';
import type { Case, TimelineEvent, EvidenceItem } from '../../types';

interface CourtDossierModalProps {
  isOpen: boolean;
  onClose: () => void;
  currentCase: Case;
  timelineEvents: TimelineEvent[];
  evidenceList: EvidenceItem[];
}

export const CourtDossierModal: React.FC<CourtDossierModalProps> = ({
  isOpen,
  onClose,
  currentCase,
  timelineEvents,
  evidenceList
}) => {
  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/85 backdrop-blur-md flex items-center justify-center p-4">
      <div className="bg-dark-900 border border-gray-700 rounded-2xl w-full max-w-4xl h-[90vh] overflow-hidden shadow-2xl flex flex-col">
        {/* Top Action Bar (hidden in print) */}
        <div className="p-4 border-b border-gray-800 bg-dark-800 flex items-center justify-between print:hidden">
          <div className="flex items-center space-x-2">
            <Shield className="w-5 h-5 text-indigo-400" />
            <h3 className="text-sm font-bold text-white">Court-Admissible Case Dossier Generator</h3>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handlePrint}
              className="flex items-center space-x-1.5 bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs py-1.5 px-3.5 rounded-lg transition-colors shadow"
            >
              <Printer className="w-4 h-4" />
              <span>Print / Save as PDF</span>
            </button>

            <button onClick={onClose} className="text-gray-400 hover:text-white p-1">
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Dossier Document Printable Area */}
        <div className="flex-1 overflow-y-auto p-8 bg-white text-gray-900 font-serif leading-normal print:p-0">
          {/* Header Seal */}
          <div className="text-center border-b-2 border-gray-900 pb-4 mb-6">
            <div className="text-xs font-bold tracking-widest text-gray-600 uppercase">
              CONFIDENTIAL • LAW ENFORCEMENT INTELLIGENCE MEMORANDUM
            </div>
            <h1 className="text-xl font-bold tracking-wider mt-1 text-gray-900">
              SPECIAL INVESTIGATION DOSSIER & EVIDENCE INTEGRITY RECORD
            </h1>
            <div className="text-xs text-gray-600 mt-1 font-sans">
              Generated by SPEMASS Decision-Support System • Case Ref: <span className="font-bold">{currentCase.case_id}</span>
            </div>
          </div>

          {/* Case Metadata Grid */}
          <div className="grid grid-cols-2 gap-4 text-xs font-sans mb-6 bg-gray-100 p-4 rounded border border-gray-300">
            <div>
              <div><span className="font-bold">Case Title:</span> {currentCase.title}</div>
              <div><span className="font-bold">Classification:</span> {currentCase.classification}</div>
              <div><span className="font-bold">Status:</span> {currentCase.status}</div>
            </div>
            <div>
              <div><span className="font-bold">Lead Officer:</span> {currentCase.lead_investigator}</div>
              <div><span className="font-bold">Date of Sealing:</span> {new Date().toLocaleDateString()}</div>
              <div><span className="font-bold">Verified Evidence Items:</span> {evidenceList.length}</div>
            </div>
          </div>

          {/* Section 1: Executive Case Synopsis */}
          <div className="mb-6">
            <h2 className="text-sm font-bold uppercase tracking-wider border-b border-gray-400 pb-1 mb-2">
              1. Executive Investigation Synopsis
            </h2>
            <p className="text-xs text-gray-800 leading-relaxed font-sans">
              {currentCase.description || "Forensic financial investigation into organized smuggling and hawala syndicates operating across multiple jurisdictions."}
            </p>
          </div>

          {/* Section 2: Chronological Timeline */}
          <div className="mb-6">
            <h2 className="text-sm font-bold uppercase tracking-wider border-b border-gray-400 pb-1 mb-2">
              2. Reconstructed Incident Chronology
            </h2>
            <table className="w-full text-left text-xs font-sans border-collapse border border-gray-300">
              <thead>
                <tr className="bg-gray-200">
                  <th className="border border-gray-300 p-1.5">Timestamp</th>
                  <th className="border border-gray-300 p-1.5">Event Title & Location</th>
                  <th className="border border-gray-300 p-1.5">Evidence ID</th>
                </tr>
              </thead>
              <tbody>
                {timelineEvents.map((evt) => (
                  <tr key={evt.id} className="border-t border-gray-200">
                    <td className="border border-gray-300 p-1.5 font-mono text-[11px]">{new Date(evt.start_time).toLocaleString()}</td>
                    <td className="border border-gray-300 p-1.5">
                      <div className="font-bold">{evt.title}</div>
                      <div className="text-gray-600 text-[10px]">{evt.summary} ({evt.location_name})</div>
                    </td>
                    <td className="border border-gray-300 p-1.5 font-mono text-[10px] text-gray-700">{evt.evidence_id || 'AUTHENTICATED'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Section 3: Evidence Cryptographic Hashes & Blockchain Ledger */}
          <div className="mb-6">
            <h2 className="text-sm font-bold uppercase tracking-wider border-b border-gray-400 pb-1 mb-2">
              3. Forensic Evidence SHA-256 Registry & Blockchain Anchors
            </h2>
            <table className="w-full text-left text-xs font-sans border-collapse border border-gray-300">
              <thead>
                <tr className="bg-gray-200">
                  <th className="border border-gray-300 p-1.5">Evidence ID</th>
                  <th className="border border-gray-300 p-1.5">Artifact Title</th>
                  <th className="border border-gray-300 p-1.5">SHA-256 Cryptographic Hash</th>
                  <th className="border border-gray-300 p-1.5">Integrity Status</th>
                </tr>
              </thead>
              <tbody>
                {evidenceList.map((ev) => (
                  <tr key={ev.evidence_id} className="border-t border-gray-200">
                    <td className="border border-gray-300 p-1.5 font-mono font-bold">{ev.evidence_id}</td>
                    <td className="border border-gray-300 p-1.5">{ev.title}</td>
                    <td className="border border-gray-300 p-1.5 font-mono text-[9px] break-all">{ev.sha256_hash}</td>
                    <td className="border border-gray-300 p-1.5 font-mono text-emerald-700 font-bold">{ev.integrity_status}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Section 4: Formal Custody Attestation */}
          <div className="pt-6 border-t-2 border-gray-900 text-xs font-sans flex justify-between items-end">
            <div>
              <div className="font-bold">Cryptographic Ledger Attestation:</div>
              <div className="text-[10px] text-gray-600">All evidence digests anchored to tamper-evident blockchain ledger.</div>
            </div>

            <div className="text-center">
              <div className="w-48 border-b border-gray-900 mb-1"></div>
              <div className="font-bold">{currentCase.lead_investigator}</div>
              <div className="text-[10px] text-gray-600">Investigating Officer Seal & Signature</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
